### ISSUE TITLE
Window closes after 9 seconds using Yode.

### ISSUE THREAD

**Issue by samuelnovaes** [yue/node-gui#34]
https://user-images.githubusercontent.com/16156987/141810273-4959685e-4e99-428a-b6ca-942e2cab275f.mp4

This only occurs using Yode.
Using Node, the window doesn't close.
I'm using Linux Mint 20.2.

**Comment by zcbenz** [comment]
When using Node.js to run code, the whole program will block at the `gui.MessageLoop.run()` call, and the local variables defined in the main script will not be garbage collected.

When using Yode to run code, the execution of the main script will finish immediately, and the local variables will be garbage collected as usual.

So you might notice some windows disappearing after running for some time when using Yode, this is because the JavaScript objects of the windows got garbage collected.

```js
const win = gui.Window.create({})
// win will be garbage collected after some time.
```

And this problem can be solved by keeping a global reference of the window.

```js
global.win = gui.Window.create({})
global.win = win
// or
global.windowManager = new Set()
windowManager.add(win)
```

**Comment by samuelnovaes** [comment]
It worked for me. Thanks!
