### ISSUE TITLE
No build for Node.js 17

### ISSUE THREAD

**Issue by mohd-akram** [yue/node-gui#35]
Also, why doesn't it try to build locally in this case?

**Comment by zcbenz** [comment]
Fixed with https://github.com/yue/yue/commit/85b77e3203a00eaab669daa423e721c636c8c09b.

This module provides prebuilt binaries because it is easier this way to support all architectures, as node-gyp does not have reasonable support for cross compilation. But I think we should eventually support building from source code as fallback.
